#%RAML 1.0 NamedExample
value: |
 [
          {
            "productId": "eb8c8ca7-3c42-4489-a820-3aa138430b75",
            "productType": "Dedicated Desk 1",
            "location": "Minneapolis", 
            "subscriptionMethod": "monthly",
            "timeUnit": "month",
            "amount": 500
            }]